spring.application.name=${SPRING_APP_NAME:gamebackend}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:true}

spring.jpa.properties.hibernate.jdbc.time_zone=Europe/Kyiv

logging.level.me.paulschwarz=DEBUG

hf.token=${HF_TOKEN}

logging.file.name=logs/app.log
logging.level.root=INFO

stripe.api.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

server.tomcat.connection-timeout=5000
server.tomcat.max-threads=200

jwt.secret=3f9a8c2d1b7e4f6a9d0c5e8f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0

server.port=${PORT:8080}
